config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/pynblint
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/cessda/cessda.ai.mcp.openaire:
      branch: 0.1.0
      repo: https://github.com/cessda/cessda.ai.mcp.openaire.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/cessda/cessda.ai.mcp.openaire git:
        commands:
        - /usr/bin/env sh .sqa/script.pasty-burgundy-birman.sh
        container: qc.acc_hasty-periwinkle-jaguar
  QC.Doc:
    repos:
      github.com/cessda/cessda.ai.mcp.openaire find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-lavender-mongrel.sh
        container: qc.doc_ugly-cerise-ibis
      github.com/cessda/cessda.ai.mcp.openaire git:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-myrtle-sponge.sh
        container: qc.doc_sleepy-alizarin-mau
      github.com/cessda/cessda.ai.mcp.openaire markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-orchid-dugong.sh
        container: qc.doc_grumpy-cinnamon-bison
  QC.Lic:
    repos:
      github.com/cessda/cessda.ai.mcp.openaire licensee:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-olivine-tamarin.sh
        container: qc.lic_ugly-russet-skunk
  QC.Sec:
    repos:
      github.com/cessda/cessda.ai.mcp.openaire bandit:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-blue-quoll.sh
        container: qc.sec_crabby-black-bloodhound
  QC.Sty:
    repos:
      github.com/cessda/cessda.ai.mcp.openaire flake8:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-beige-grouse.sh
        container: qc.sty_cloudy-sangria-dachsbracke
      github.com/cessda/cessda.ai.mcp.openaire hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.messy-ecru-setter.sh
        container: qc.sty_shabby-indigo-albatross
      github.com/cessda/cessda.ai.mcp.openaire jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-chocolate-wolf.sh
        container: qc.sty_hazy-grey-dachsbracke
  QC.Uni:
    repos:
      github.com/cessda/cessda.ai.mcp.openaire pytest:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-wisteria-tang.sh
        container: qc.uni_cheeky-platinum-fowl
  QC.Ver:
    repos:
      github.com/cessda/cessda.ai.mcp.openaire get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-chocolate-havanese.sh
        container: qc.ver_gimpy-pink-dingo
timeout: 5400
