config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/pynblint
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/cessda/cessda.ai.mcp.openaire:
      branch: main
      repo: https://github.com/cessda/cessda.ai.mcp.openaire.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/cessda/cessda.ai.mcp.openaire git:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-ivory-chinchilla.sh
        container: qc.acc_cozy-maroon-indri
  QC.Doc:
    repos:
      github.com/cessda/cessda.ai.mcp.openaire find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.surly-indigo-newfoundland.sh
        container: qc.doc_wheezy-crimson-tuatara
      github.com/cessda/cessda.ai.mcp.openaire git:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-magnolia-kingfisher.sh
        container: qc.doc_sunny-seashell-skunk
      github.com/cessda/cessda.ai.mcp.openaire markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-ochre-crane.sh
        container: qc.doc_flimsy-aquamarine-lynx
  QC.Lic:
    repos:
      github.com/cessda/cessda.ai.mcp.openaire licensee:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-seashell-buzzard.sh
        container: qc.lic_snoopy-cinnabar-antelope
  QC.Sec:
    repos:
      github.com/cessda/cessda.ai.mcp.openaire bandit:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-russet-fox.sh
        container: qc.sec_freaky-sapphire-wolfhound
  QC.Sty:
    repos:
      github.com/cessda/cessda.ai.mcp.openaire flake8:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-silver-frigatebird.sh
        container: qc.sty_lovely-asparagus-otter
      github.com/cessda/cessda.ai.mcp.openaire hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.flabby-cinnamon-tuatara.sh
        container: qc.sty_leaky-xanthic-quokka
      github.com/cessda/cessda.ai.mcp.openaire jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.homely-pumpkin-oriole.sh
        container: qc.sty_frumpy-cardinal-dugong
  QC.Uni:
    repos:
      github.com/cessda/cessda.ai.mcp.openaire pytest:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-tomato-shrew.sh
        container: qc.uni_lovely-platinum-kangaroo
  QC.Ver:
    repos:
      github.com/cessda/cessda.ai.mcp.openaire get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.sickly-eggplant-squirrel.sh
        container: qc.ver_snoopy-ivory-weasel
timeout: 5400
